"""Initial

Revision ID: 76a872d40d67
Revises: 22a750ea2812
Create Date: 2022-03-17 16:27:32.722173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a872d40d67'
down_revision = '22a750ea2812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('languages_url', sa.String(), nullable=True))
    op.drop_constraint('repos_user_id_fkey', 'repos', type_='foreignkey')
    op.drop_column('repos', 'language')
    op.drop_column('repos', 'language_url')
    op.drop_column('repos', 'repo_id')
    op.drop_column('repos', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('language_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('repos', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('repos_user_id_fkey', 'repos', 'users', ['user_id'], ['id'])
    op.drop_column('repos', 'languages_url')
    # ### end Alembic commands ###
